/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lukman
 */

import Backend.Gedung;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

public class TabelGedung extends javax.swing.JFrame {

    /**
     * Creates new form Lapangan
     */
//    private String jamnya, selesai, tanggalnya, idGedung;
//    int totHarga;
//    DefaultTableModel model;
//    DefaultTableModel model2;
//    DefaultTableModel model3;
    
    
    
    
    public TabelGedung() {
        
//        String [] judul ={"ID_Member","Nama","No_HP"};
//        String [] judul3 ={"ID_Gedung","Ruang Ganti","Nama Gedung","Alamat"};
//        String [] judul2 ={"ID_Penyewaan","ID_Member","ID_Gedung","Tanggal","Mulai","Selesai","Total Harga"};
//        model = new DefaultTableModel(judul, 0);
//        model2 = new DefaultTableModel(judul2, 0);
//        model3 = new DefaultTableModel(judul3, 0);
//        tabelMember.setModel(model);
//        tabelSewa.setModel(model2);
//        tabelGedung.setModel(model3);
//        tampilkan();
//        tampilkan2();
        
        initComponents();
        tampilkanGedung();
        kosongkanFormGedung();
        
//        tampil_combo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gedung = new javax.swing.JTextField();
        rGanti = new javax.swing.JTextField();
        namaGedung = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelGedung = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        tambahGedung = new javax.swing.JButton();
        hapusGedung = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(157, 204, 142));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Welcome, ADMIN");

        jLabel3.setText("ID_Gedung");

        jLabel4.setText("Ruang Ganti");

        jLabel10.setText("Nama Gedung");

        gedung.setEditable(false);

        rGanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rGantiActionPerformed(evt);
            }
        });

        namaGedung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaGedungActionPerformed(evt);
            }
        });

        tabelGedung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelGedung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelGedungMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelGedung);
        if (tabelGedung.getColumnModel().getColumnCount() > 0) {
            tabelGedung.getColumnModel().getColumn(3).setMinWidth(165);
        }

        jLabel16.setText("Alamat");

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        tambahGedung.setText("Save");
        tambahGedung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahGedungActionPerformed(evt);
            }
        });

        hapusGedung.setText("Delete");
        hapusGedung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusGedungActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jButton1.setText("Layani Pemesanan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(gedung, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(namaGedung, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rGanti, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alamat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(hapusGedung, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(tambahGedung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gedung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rGanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaGedung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahGedung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusGedung))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );

        jTabbedPane1.addTab("ADMIN", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTabbedPane1)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        kosongkanFormGedung();
    }//GEN-LAST:event_clearActionPerformed

    private void hapusGedungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusGedungActionPerformed
        DefaultTableModel model = (DefaultTableModel)tabelGedung.getModel();
        int row = tabelGedung.getSelectedRow();

        Gedung gd = new Gedung().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        gd.delete();
        kosongkanFormGedung();
        tampilkanGedung();

    }//GEN-LAST:event_hapusGedungActionPerformed

    private void tambahGedungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahGedungActionPerformed
        Gedung gd = new Gedung();
        gd.setId_gedung(Integer.parseInt(gedung.getText()));
        gd.setR_ganti(Integer.parseInt(rGanti.getText()));
        gd.setNama(namaGedung.getText());
        gd.setAlamat(alamat.getText());
        gd.save();
        gedung.setText(Integer.toString(gd.getId_gedung()));
        tampilkanGedung();
        //        tampil_combo();

    }//GEN-LAST:event_tambahGedungActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void tabelGedungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelGedungMouseClicked
        DefaultTableModel model = (DefaultTableModel)tabelGedung.getModel();
        int row = tabelGedung.getSelectedRow();

        gedung.setText(model.getValueAt(row, 0).toString());
        rGanti.setText(model.getValueAt(row, 1).toString());
        namaGedung.setText(model.getValueAt(row, 2).toString());
        alamat.setText(model.getValueAt(row, 3).toString());

    }//GEN-LAST:event_tabelGedungMouseClicked

    private void namaGedungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaGedungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaGedungActionPerformed

    private void rGantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rGantiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rGantiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new TabelPenyewaan().setVisible(true);
            dispose();
            }
            });
    }//GEN-LAST:event_jButton1ActionPerformed
    // kosongkan form-form
    private void kosongkanFormGedung() {
        gedung.setText("0");
        rGanti.setText("0");
        namaGedung.setText("");
        alamat.setText("");
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelGedung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelGedung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelGedung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelGedung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelGedung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton clear;
    private javax.swing.JTextField gedung;
    private javax.swing.JButton hapusGedung;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField namaGedung;
    private javax.swing.JTextField rGanti;
    private javax.swing.JTable tabelGedung;
    private javax.swing.JButton tambahGedung;
    // End of variables declaration//GEN-END:variables

//    private void tampilkan() {
//        int row = tabelMember.getRowCount();
//        for(int a=0; a<row; a++) {
//            model.removeRow(0);
//        }
//        try {
//            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tugasakhir","root","");
//            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM member");
//            while(rs.next()) {
//                String data [] = {rs.getString(1), rs.getString(2), rs.getString(3)};
//                model.addRow(data);
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Lapangan.class.getName()).log(Level.SEVERE, null, ex);
//        }
//       
//    }

//    private void tampilkan2() {
//        int row = tabelSewa.getRowCount();
//        for(int a=0; a<row; a++) {
//            model2.removeRow(0);
//        }
//        try {
//            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tugasakhir","root","");
//            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM penyewaan");
//            while(rs.next()) {
//                String data [] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7)};
//                model2.addRow(data);
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Lapangan.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
//    private void tampilkan3() {
//        int row = tabelGedung.getRowCount();
//        for(int a=0; a<row; a++) {
//            model3.removeRow(0);
//        }
//        try {
//            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tugasakhir","root","");
//            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM gedung");
//            while(rs.next()) {
//                String data [] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
//                model3.addRow(data);
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Lapangan.class.getName()).log(Level.SEVERE, null, ex);
//        }
//       
//    }
    
    public void tampilkanGedung() {
        String [] kolom ={"ID_Gedung","Ruang Ganti","Nama Gedung","Alamat"};
        ArrayList<Gedung> list = new Gedung().getAll();
        Object rowData[] = new Object[4];
        
        tabelGedung.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Gedung gd : list) {
            rowData[0] = gd.getId_gedung();
            rowData[1] = gd.getR_ganti();
            rowData[2] = gd.getNama();
            rowData[3] = gd.getAlamat();
            
            ((DefaultTableModel)tabelGedung.getModel()).addRow(rowData);
        }
    }
    
//    public void tampil_combo() {
//        int row = id_gedung.getItemCount();
//        for(int i=0; i<row; i++) {
//            id_gedung.removeItemAt(0);
//        }
//        try {
//            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/tugasakhir","root","");
//            ResultSet rs = cn.createStatement().executeQuery("SELECT * FROM gedung");
//            while(rs.next()) {
//                id_gedung.addItem(rs.getString("id_gedung"));
//            } 
//            
////            rs.last();
////            int jumlahGedung = rs.getRow();
////            rs.first();
//            
//        } catch(Exception ex) {
//            
//        }
//    }
    
}
